### ISSUE TITLE
Caffeine does inhibit screen dimming in Gnome3 without gnome-screensaver

### ISSUE THREAD

**Issue by HarmtH** [hobarrera/caffeine-ng#11]
The code checks if gnome-screensaver is running, which is not necessary imho. 'gnome-session' will dim the screen if it is enabled in the power options.

**Comment by hobarrera** [comment]
We really should check if it implements the `org.freedesktop.PowerManagement.Inhibit` spec. If it does, I'll give that priority when [checking inhibition method](https://github.com/hobarrera/caffeine-ng/blob/master/caffeine/core.py#L303-L305).

**Comment by HarmtH** [comment]
I haven't checked the freedesktop options, but [this](https://github.com/HarmtH/caffeine-ng/blob/master/caffeine/core.py#L300-L301) works for me.

**Comment by HarmtH** [comment]
It seems Gnome3 doesn't implement org.freedesktop.PowerManagement, or at least I can't find it with d-feet.

I think the check for screensavers is redundant, as screen dimming/blanking should also be inhibited when no screensaver program is running.

**Comment by hobarrera** [comment]
> I think the check for screensavers is redundant, as screen dimming/blanking should also be inhibited when no screensaver program is running.

Apparently it is. The check may be there for historial reasons, but I can't confirm that.
Would you mind sending a PR for this?

Thanks.

**Comment by HarmtH** [comment]
Sure, done. I don't use KDE so haven't touched that btw.

**Comment by hobarrera** [comment]
Thanks. I'll close this and let's move discussion to #12.  
I need to set up VMs with different environemnts to properly test this, but I've been postponing this due to time constraints.

**Comment by hobarrera** [comment]
Closed by #12.
