### ISSUE TITLE
A white icon for a dark background

### ISSUE THREAD

**Issue by Deuchnord** [hobarrera/caffeine-ng#13]
The icon is not very visible if the background is dark.

As it is some difficult to adapt automatically the icon for this, the better way to solve this should be to add an option to toggle the icon theme between the current dark version and a white version.

An example on Arch Linux with Cinnamon desktop environment: ![Capture](https://cloud.githubusercontent.com/assets/7600265/6525134/084457e6-c402-11e4-8c86-76fd44399494.png)

**Comment by hobarrera** [comment]
Icon themes can override caffeine's icon (any some do). It's not up to individual apps to have configurable icons, that's what we have icon themes for.

elementary-xfce-dark, [for example](https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce-dark/panel/22/caffeine-cup-empty.svg), has a lighter one.

If your icon theme does not override it, you can add your own to it, just place them these locations:

    /usr/share/icons/THEME_NAME/panel/22/caffeine-cup-empty.svg
    /usr/share/icons/THEME_NAME/panel/22/caffeine-cup-full.svg
