### ISSUE TITLE
Caffeine-ng uses excessive amounts of memory

### ISSUE THREAD

**Issue by protist** [hobarrera/caffeine-ng#15]
I have two users logged into my computer. Each has caffeine running, and each instance is using ~4.5 GB of RAM. I tried to quit caffeine-ng from the system tray, and this took about a minute, running at 100% of one core.

I then started one instance up again, and it started with 51 MB of RAM, before increasing to 57 MB within a few minutes. FWIW my uptime was 5 days. I'm not sure if there are any debugging options, but I'm happy to troubleshoot more.

KDE
Arch Linux
caffeine-ng 3.1-1 (via AUR)

**Comment by hobarrera** [comment]
I've actually noticed this some time ago, but haven't had gotten around to debugging it (I must admit, it only went up to a few hundred MiB for me, never that much).

I did many of the code clean ups with the intention of uncovering this issue (as well as a few others).

I noticed some zombie processes left for notify-send, so I intend to see if it's related. Not sure what's going wrong though, but since python uses managed memory, I'm guessing it's something related to gtk/dbus interactions.

There's no need for you to debug this yourself, since I can reproduce this myself.

**Comment by protist** [comment]
Thanks for that. I'll keep an eye out for notify-send, but I didn't notice anything previously. In fact, I didn't even realise that caffeine-ng used notify-send. I don't remember any related notifications.

One other minor problem is that when I start `caffeine` from the command line, I get an warning `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`. I presume that this is unrelated to the memory leak, but only mention it since caffeine-ng might contain some deprecated interactions with gtk.

**Comment by hobarrera** [comment]
> Thanks for that. I'll keep an eye out for notify-send, but I didn't notice anything previously. In fact, I didn't even realise that caffeine-ng used notify-send. I don't remember any related notifications.

No, sorry, scrub that, I got confused with another app (not of my own making) that left behind lots of zombie `notify-send` processes. caffeine-ng doesn't do that. Sorry, my mistake.

**Comment by protist** [comment]
No worries. I'll keep an eye on caffeine-ng's memory usage over the next couple of days, and see if it correlates with anything I'm doing. At present, after 40 minutes or so, it's only gone from 51 to 61 MB. At that rate, it'll "only" increase to 1.8 GB after five days, which is considerably less that what I've seen, so perhaps there's something I'm doing that is irritating it.

**Comment by protist** [comment]
I'm not really sure how relevant it is, but 4 hours later it was using 73 MB, 8 hours later it was 120 MB, 20 hours later it was 212 MB, and 23 hours later it was 269 MB. I can't really connect the increase to anything specific that I'm doing. It seems to increase steadily regardless of my activity.

**Comment by ert65** [comment]
I have that problem too and i think the memory consumption grows when caffeine automaticaly turn screensaver off with fullscreen apps. I hope the problem will be solved because after 72 four hours uptime, caffeine took 3,5 gb memory ;(. P.S: I am using arch with cinnamon (64bit)

**Comment by protist** [comment]
That sounds plausible, since I tend to see it more in the evening, when I'm using fullscreen more. Also, is there a way to disable the fullscreen functionality of caffeine-ng? I don't really want this functionality, and disabling it would also help us troubleshoot. FWIW I never saw these memory problems about a year ago when I used the old caffeine, so it's presumably a regression, perhaps caused by the introduction of new features.

**Comment by hobarrera** [comment]
Latest from git has some changes that attempt to address the issue, but I'm not 100% sure if they fix it or not (required further testing on a high-uptime PC, and I've been away from my desktop lately).

You might want to try it if you like. Otherwise I'll test it better during the week.

**Comment by protist** [comment]
Thanks for that. So far, it seems pretty good. When launched, it used 50.3 MB; 6 hours later it's at 51.7 MB. Much better than before, so far. I'll report back later with more numbers, after a bit of full-screening tonight.

(Also, is there a way to disable the fullscreen trigger for caffeine-ng?)

**Comment by hobarrera** [comment]
> (Also, is there a way to disable the fullscreen trigger for caffeine-ng?)

No. Is this a feature you actually feel that you need?

**Comment by protist** [comment]
Yes, I'd definitely turn it off if it were possible. For me, fullscreen doesn't necessarily equate with not wanting the computer to sleep. Sure, I might be watching a movie in fullscreen, but I might also be editing a text document in fullscreen. I much prefer the finer control of manually listing `vlc`, etc. in the automatic activation section.

**Comment by protist** [comment]
Now 10 hours later, after a bit of fullscreening, I'm at 47.5 MB, which is *less* than I started with, so I'm pretty sure it's fixed. Thanks very much for that. (I'll close this issue, but should I open a new issue for preventing fullscreen trigger, or is this something that you wouldn't want to change?)

**Comment by hobarrera** [comment]
Thanks for taking the time to monitor this properly. I've been coming and going and haven't really sat down with a long enough uptime.

Feel free to open a new issue as a feature request. I won't give this the same urgency as a memory leak, but I'll look at it when I get a chance. :)

**Comment by protist** [comment]
No worries. Yes, I certainly agree that this option is lower priority. I've opened a new issue #16. Thanks again.

**Comment by protist** [comment]
Just to confirm, 24 hours later caffeine-ng is still using only 45.5 MB (even less than the last timepoint). Nice fix, and thanks again.

**Comment by hobarrera** [comment]
Thanks for the feedback, that's great news. I'm still amazed by the huge impact of such subtle changes.
