### ISSUE TITLE
Memory leak on KDE

### ISSUE THREAD

**Issue by varlesh** [hobarrera/caffeine-ng#21]
Uptime 17 h 22 min - caffeine-ng use 540 mb RAM. 
Arch Linux x86_64
KDE 5.4.1
Caffeine-ng 3.1-1
![9](https://cloud.githubusercontent.com/assets/8083855/10046483/a108b910-6211-11e5-8baa-0477a652cef5.png)
![10](https://cloud.githubusercontent.com/assets/8083855/10046506/bc8194c8-6211-11e5-81b6-4102c87ca863.png)

**Comment by egon0** [comment]
Seems to be a general Arch Linux related bug. I have seen the same problem on XFCE and Cinnamon. So it's definiteley not only KDE related. The problem exists for quite some time at all of my Manjaro installations.

**Comment by hobarrera** [comment]
Can you confirm if this is still an issue on recent versions?  I've seen no memory leaks in more recent versions, but haven't thoroughly tested KDE.

**Comment by bisby** [comment]
I see no memory leak on Arch anymore using XFCE. after several hours it's sitting at 47.3 MiB, whereas previously it would get up to 9gb+ before i had to kill it.
