### ISSUE TITLE
Cinnamon/Gnome screensaver not inhibited

### ISSUE THREAD

**Issue by hobarrera** [hobarrera/caffeine-ng#5]
(This issue got hijacked so I created a new one for the original comment, and followed up discussing here to keep things simple.)

**Comment by jrahmy** [comment]
Running Cinnamon on Arch and unfortunately caffeine-ng doesn't inhibit Cinnamon's screen locker.

I'm not sure whether or not Cinnamon uses X idleness to trigger but presumably this could be the cause? Otherwise I can open a new issue.

**Comment by hobarrera** [comment]
I don't think so. It's probably a separete issue, though not the first one reported on Mint. Regrettably, I haven't been able to set up a working VM to test this thoroughly ([1](http://forums.linuxmint.com/viewtopic.php?f=90&t=184039)).

**Comment by hobarrera** [comment]
@jrahmy I haven't tested Cinnamon independently, but I've done some changes on how inhibition works that *should* either fix your scenario, (or at least provide valuable output).

Can you test this now, please?

If you encounter some issue with cinnamons screelocker, can you:
1. Upgrade to v3.0.
1. Run vía a terminal (just run `caffeine`).
1. Send me any output you see on that terminal.

Let me know if it's fixed too, so I know I can close this. Otherwise I'll try to spin up a VM sometime soon.

Thanks.

**Comment by jrahmy** [comment]
Can do. It doesn't seem like 3.0 has been pushed yet? or I would build and test it now.

**Comment by hobarrera** [comment]
Had forgotten to push. 😅

**Comment by jrahmy** [comment]
It's not inhibiting the screensaver, but there's more output than before.

It seems to think most/all of the inhibitors are applicable, and the gnome inhibitor is throwing some exceptions.

```$ caffeine
INFO:caffeine.core:Caffeine is starting up...
INFO:caffeine.main:User has clicked the Caffeine icon
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.GnomeInhibitor'> is applicable, running it.
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.XdgScreenSaverInhibitor'> is applicable, running it.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 45, in toggle
    self.inhibit()
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 57, in inhibit
    if not self.__proxy:
AttributeError: 'GnomeInhibitor' object has no attribute '_GnomeInhibitor__proxy'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 45, in toggle
    self.inhibit()
  File "/usr/lib/python3.4/site-packages/caffeine/inhibitors.py", line 86, in inhibit
    self.__proxy_ss.Inhibit("Caffeine", INHIBITION_REASON)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface '(null)' on object at path /ScreenSaver

INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.DpmsInhibitor'> is applicable, running it.
INFO:caffeine.core:Inhibitor <class 'caffeine.inhibitors.XorgInhibitor'> is applicable, running it.```

**Comment by jrahmy** [comment]
I'm not sure why they're all firing.. I could maybe write an inhibitor for cinnamon-screensaver though. It has a command line utility, cinnamon-screensaver-command for controlling it.

There's no option to "disable" it, but the daemon could be gracefully stopped with ```cinnamon-screensaver-command --exit``` and restarted by running ```cinnamon-screensaver```.

**Comment by hobarrera** [comment]
> I'm not sure why they're all firing.. I could maybe write an inhibitor for cinnamon-screensaver though. It has a command line utility, cinnamon-screensaver-command for controlling it.

The one for gnome should work (the internals for cinnamon and gnome are the same), but it's broken.

Can you try the latest from git now? Otherwise, I'll have to install a VM with gnome on it to test properly.

**Comment by jrahmy** [comment]
Latest error is ```dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface '(null)' on object at path /ScreenSaver```.

I'm not sure how far they've deviated from Gnome, though Cinnamon did start as a fork of Gnome 3 and uses GTK.

**Comment by hobarrera** [comment]
Even with that error, your screensaver *should* be inhibited (I've noticed two inhibitors being triggered, the non-gnome one is failing).

Can you confirm that?

**Comment by jrahmy** [comment]
You're right, the Gnome inhibitor is working, and I guess the applicable method for XdgScreenSaverInhibitor is returning true.

It works :smiley:

**Comment by hobarrera** [comment]
Indeed, something's exposing the Xdg interface, but not responding to it properly. I'll look into that later on with lower priority.

Glad to hear it works now!
